# Assignment_1
If you copy codes from previous answers, explain each step. No explanation is `0 points`.

##  Part 1.Data types


a.Declare one variable for each one these types: : int , float , string , boolean. [1.25 pts.]
- Print  the varible's type using  type () function




In [1]:
int_var = 10  # Integer variable
float_var = 10.5  # Floating-point variable
string_var = "Hello, world!"  # String variable
boolean_var = True  # Boolean variable

In [2]:
print(type(int_var))  # Output: <class 'int'>
print(type(float_var))  # Output: <class 'float'>
print(type(string_var))  # Output: <class 'str'>
print(type(boolean_var))  # Output: <class 'bool'>

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


 b. Using only the following inputs: ```5``` and ```2```  ,  work the  operators to get the output  : ```50``` [1.25 pts.]

In [3]:
result = 5 * (5 * 2)  # 5 * 10 = 50
print(result)  # Output: 50

50


c. Evaluate if the output of the previous excercise is over 100. Create a variable that makes this evaluation. (Hint: It would be a boolean). [1.25 pts.]

In [4]:
is_over_100 = result > 100
print(is_over_100)  # Output: False

False


d. Create a variable equal to a list that contains:  [1.25 pts.]
- a string,
- a boolean,
- two numeric values ( of any kind)  and
- a  list of two strings with the names of your favourite musical artists. 

In [5]:
mixed_list = ["Python", True, 3.14, 42, ["Coldplay", "Imagine Dragons"]]
print(mixed_list)

['Python', True, 3.14, 42, ['Coldplay', 'Imagine Dragons']]


## Part 2. Containers

e. Create a tuple with 3 elements. Explain why you can't modify it.  [1.25 pts.]

In [6]:
tuple_var = (1, 2, 3)
print(tuple_var)

(1, 2, 3)


In [7]:
# Tuples cannot be modified: tuple_var[0] = 10 would raise an error
tuple_var[0] = 10

TypeError: 'tuple' object does not support item assignment

f.Create a dictionary with at least 3 different  keys and values . [1.25 pts.]

In [8]:
dictionary = {"name": "Michael", "age": 22, "city": "Lima"}
print(dictionary)

{'name': 'Michael', 'age': 22, 'city': 'Lima'}


g.We got the next courses list: [3.75 pts.]

In [18]:
courses = ["History", "Economy", "Anthropology", "Sociology ", "Literature"]

g.1.Add tree additional courses in 3 different ways( one for each way): [0.9375 pts.]
   - Sum (+) a list that contains an additional course. 
   - Use append. 
   - Use extend. 

In [19]:
courses = courses + ["Philosophy"]  # Using + operator

In [20]:
courses.append("Political Science")  # Using append

In [21]:
courses.extend(["Psychology"])  # Using extend

In [22]:
print(courses)

['History', 'Economy', 'Anthropology', 'Sociology ', 'Literature', 'Philosophy', 'Political Science', 'Psychology']


g.2.Use the indexation to stress _Sociology_. [0.9375 pts.]

In [23]:
print(courses[3].upper())  # Output: SOCIOLOGY

SOCIOLOGY 


g.3 Remove your least favourite course [0.9375 pts.]

In [24]:
courses.remove("Economy")  # Assuming Economy is the least favorite
print(courses)

['History', 'Anthropology', 'Sociology ', 'Literature', 'Philosophy', 'Political Science', 'Psychology']


g.4. Invert the list [0.9375 pts.]

In [25]:
courses.reverse()
print(courses)

['Psychology', 'Political Science', 'Philosophy', 'Literature', 'Sociology ', 'Anthropology', 'History']


h.Create a dictionary that representst a fruits inventory: [1.25 pts.]
 - Add at least 5 fruits to the inventory
- Print the amount of apples in stock 
- Modify the amount of grapes


In [15]:
fruit_inventory = {"Apples": 10, "Bananas": 15, "Oranges": 8, "Grapes": 12, "Mangoes": 6}
print(fruit_inventory["Apples"])  # Print the amount of apples

10


In [16]:
fruit_inventory["Grapes"] = 20  # Modify the amount of grapes
print(fruit_inventory)

{'Apples': 10, 'Bananas': 15, 'Oranges': 8, 'Grapes': 20, 'Mangoes': 6}


i.  Write a dictionary with the local GMT of the nexts cities: [1.25 pts.]
- Antananarivo, Madagascar, 
- Beirut, Lebanon, 
- Jakarta, Indonesia, 
- Teherán, Iran, 
- Vientiane, Laos, 



Hint: Lima would be: `"Lima": -5`

In [27]:
gmt_dict = {
    "Antananarivo": 3,
    "Beirut": 2,
    "Jakarta": 7,
    "Teherán": 3.5,
    "Vientiane": 7
}

print(gmt_dict)

{'Antananarivo': 3, 'Beirut': 2, 'Jakarta': 7, 'Teherán': 3.5, 'Vientiane': 7}


 j.Add the nexts cities to the dictionary: [1.25 pts.]
- Astana, Kazakhstan,
- Uagadugú, Burkina Faso,
- Balmopan, Belize

In [28]:
gmt_dict.update({
    "Astana": 6,
    "Uagadugú": 0,
    "Balmopan": -6
})

print(gmt_dict)

{'Antananarivo': 3, 'Beirut': 2, 'Jakarta': 7, 'Teherán': 3.5, 'Vientiane': 7, 'Astana': 6, 'Uagadugú': 0, 'Balmopan': -6}


# Part 3. Numpy


k.Create an array with 10 aleatory values that go from 0 to 9 [1.25 pts.]

In [30]:
import numpy as np

In [31]:
random_array = np.random.randint(0, 10, 10)
print(random_array)


[5 4 9 4 7 0 1 5 7 2]


l.Create a matrix 3x2 fill with zeros [1.25 pts.]

In [32]:
zero_matrix = np.zeros((3, 2))
print(zero_matrix)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


m.Sum two arrays and then multiply the output by an scalar [1.25 pts.]

In [33]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

In [34]:
result_array = (array1 + array2) * 2  # Scalar multiplication
print(result_array)

[10 14 18]


n.Create 2 arrays with the values that you wish : [1.25 pts.]
- Concatenate vertically 
- Concatenate horizontally 

In [35]:
# Create 2 arrays
array3 = np.array([[1, 2], [3, 4]])
array4 = np.array([[5, 6], [7, 8]])

In [36]:
# Vertical concatenation
vertical_concat = np.vstack((array3, array4))
print(vertical_concat)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [37]:
# Horizontal concatenation
horizontal_concat = np.hstack((array3, array4))
print(horizontal_concat)

[[1 2 5 6]
 [3 4 7 8]]


## SOLVED