## Part 1.Data types
a. Declare one variable for each one these types: : int , float , string , boolean.

Print the varible's type using type () function

In [ ]:
my_int = 15          # Integer
print(type(my_int))

my_float = 11.5      # Float
print(type(my_float))

my_string = "Yer"  # String
print(type(my_string))

my_bool = True       # Boolean
print(type(my_bool))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


b. Using only the following inputs: 5 and 2 , work the operators to get the output : 50

In [ ]:
result = 5 * (2 * 5)
result

50

c. Evaluate if the output of the previous excercise is over 100. Create a variable that makes this evaluation. (Hint: It would be a boolean).

In [20]:
result = 50
is_over_100 = result > 100
print(is_over_100)

False


d. Create a variable equal to a list that contains:

*   a string,
*   a boolean,
*   two numeric values (of any kind) and
*   a list of two strings with the names of your favourite musical artists.

In [21]:
my_list = [
    "Hey, dude!",       # A string
    True,                  # A boolean
    46,                    # A numeric value (integer)
    2.18,                  # Another numeric value (float)
    ["Lady gaga", "Queen"]  # A list of two strings
    ]
print(my_list)

['Hey, dude!', True, 46, 2.18, ['Lady gaga', 'Queen']]


## Part 2. Containers
e. Create a tuple with 3 elements. Explain why you can't modify it.

In [ ]:
superheros = ("Iron Man", "Batman", "Spiderman")
superheros

# A tuple can't be modified because it's an immutable element. It's desinged to ensure data security and consistence.

('Iron Man', 'Batman', 'Spiderman')

f. Create a dictionary with at least 3 different keys and values.

In [ ]:
music = {"singer" : "Sam Smith", "song" : "Fire on Fire", "first album" : "In the lonely hour"}
music

{'singer': 'Sam Smith',
 'song': 'Fire on Fire',
 'first album': 'In the lonely hour'}

g. We got the next courses list:

In [ ]:
courses = ["History", "Economy", "Antropology", "Sociology", "Literature"]

g.1. Add tree aditional courses in 3 different ways (one for each way).

*  Sum (+) a list that contains an additional course.
*  Use append.
*  Use extend.

In [ ]:
# Add an aditional course using sum (+)
new_course = ["Science"]

courses = courses + new_course
courses

['History', 'Economy', 'Antropology', 'Sociology', 'Literature', 'Science']

In [ ]:
# Add an aditional course using append
courses.append("Ethics")
courses

['History',
 'Economy',
 'Antropology',
 'Sociology',
 'Literature',
 'Science',
 'Ethics']

In [ ]:
# Add an aditional course using extend
courses.extend(["Geography"])
courses

['History',
 'Economy',
 'Antropology',
 'Sociology',
 'Literature',
 'Science',
 'Ethics',
 'Geography']

g.2. Use the indexation to stress Sociology. [0 pts.] Solution: print(courses[3].upper())  # Output: SOCIOLOGY

In [ ]:
courses[3]

'Sociology'

g.3. Remove your least favourite course.

In [ ]:
courses.remove("Economy")
courses

['History',
 'Antropology',
 'Sociology',
 'Literature',
 'Science',
 'Ethics',
 'Geography']

g.4. Invert the list.

In [ ]:
courses = ["History", "Antropology", "Sociology", "Literature", "Science", "Ethics", "Geography"]

courses.reverse()
courses

['Geography',
 'Ethics',
 'Science',
 'Literature',
 'Sociology',
 'Antropology',
 'History']

h. Create a dictionary that represents a fruits inventory.

*   Add at least 5 fruits to the inventory
*   Print the amount of apples in stock
*   Modify the amount of grapes

In [ ]:
fruits = {"apples" : 4, "grapes" : 2, "watermelons" : 5, "cherries" : 4, "peaches" : 3}

# Printing the amount of apples in stock
fruits["apples"]

4

In [ ]:
# Modifying the amount of grapes
fruits["grapes"] = 4
fruits

{'apples': 4, 'grapes': 4, 'watermelons': 5, 'cherries': 4, 'peaches': 3}

i. Write a dictionary with the local GMT of the next cities:

*   Antananarivo, Madagascar
*   Beirut, Lebanon,
*   Jakarta, Indonesia,
*   Teherán, Iran,
*   Vientiane, Laos

In [ ]:
GMT = {"Antananarivo" : "+3:00", "Beirut" : "+2:00", "Jakarta" : "+7:00", "Teherán" : "+3:30", "Vientianes" : "+7:00"}
GMT

{'Antananarivo': '+3:00',
 'Beirut': '+2:00',
 'Jakarta': '+7:00',
 'Teherán': '+3:30',
 'Vientianes': '+7:00'}

j. Add the next cities to the dictionary:

*   Astana, Kazakhstan,
*   Uagadugú, Burkina Faso,
*   Balmopan, Belize

In [ ]:
GMT["Astana"] = "+6:00"
GMT["Uagadugú"] = "+0:00"
GMT["Balmopan"] = "-6:00"
GMT

{'Antananarivo': '+3:00',
 'Beirut': '+2:00',
 'Jakarta': '+7:00',
 'Teherán': '+3:30',
 'Vientianes': '+7:00',
 'Astana': '+6:00',
 'Uagadugú': '+0:00',
 'Balmopan': '-6:00'}

## Part 3. Numpy
k. Create an array with 10 aleatory values that go from 0 to 9

In [23]:
import numpy as np
k = np.random.randint(0, 9, 10) #An array was created using random method
k

array([0, 1, 2, 4, 2, 4, 1, 1, 6, 6])

l. Create a matrix 3x2 fill with zeros

In [24]:
l = np.zeros ((3,2)) #A matrix was created using np.zeros and following instructions
l

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

m. Sum two arrays and then multiply the output by an scalar

In [25]:
m_1 = np.random.randint(0,3,3)
m_2 = np.random.randint(0,3,3) #two random arrays was created with 3 values from 0 to 3
m_plus = m_1+m_2
m_scalar = 3 #After that define a scalar
m_result = m_plus*m_scalar
m_result

array([ 0, 12,  6])

n. Create 2 arrays with the values that you wish :

*   Concatenate vertically
*   Concatenate horizontally

In [29]:
n_1 = np.array ([1,3,7,5,4,2])
n_2 = np.array ([0,7,4,5,9,1]) #
n_h = np.hstack((n_1, n_2)) # Using np.hstack to concatenate horizontally
n_v = np.vstack((n_1, n_2)) # Using np.vstack to concatenate horizontally
n_h

array([1, 3, 7, 5, 4, 2, 0, 7, 4, 5, 9, 1])

In [30]:
n_v

array([[1, 3, 7, 5, 4, 2],
       [0, 7, 4, 5, 9, 1]])