# Assignment_1
## Group_2
If you copy codes from previous answers, explain each step. No explanation is `0 points`.

##  Part 1.Data types


a.Declare one variable for each one these types: : int , float , string , boolean.
- Print  the varible's type using  type () function




In [255]:
a_1 = 666 # We create one variable for each type and confirmed with type function

In [256]:
type (a_1)

int

In [257]:
a_2 = 6.66

In [258]:
type (a_2)

float

In [259]:
a_3 = "lucifer"

In [260]:
type (a_3)

str

In [261]:
a_4 = False 

In [262]:
type (a_4)

bool

 b. Using only the following inputs: ```5``` and ```2```  ,  work the  operators to get the output  : ```50```

In [263]:
 b = 5 * 2 *5 # We create inputs with int and then get the result with another variable

In [264]:
b

50

c. Evaluate if the output of the previous excercise is over 100. Create a variable that makes this evaluation. (Hint: It would be a boolean).

In [265]:
 c = b > 100 # We analize that output is over 100

In [266]:
 c

False

d. Create a variable equal to a list that contains: 
- a string,
- a boolean,
- two numeric values ( of any kind)  and
- a  list of two strings with the names of your favourite musical artists. 

In [267]:
d = [ "Julian" , True, 666 , 6.66,["BTS", "EXO"] ] # We create a list with data required.

In [268]:
d

['Julian', True, 666, 6.66, ['BTS', 'EXO']]

## Part 2. Containers

e. Create a tuple with 3 elements. Explain why you can't modify it. 

In [269]:
 e = ( "Mauricio" , "Sofia" , "Julian") # We create a tuple with our names

In [270]:
e

('Mauricio', 'Sofia', 'Julian')

In [271]:
#because is inmutable so you can´t modify it. If you want to add new data, you need to create another tuple.

f.Create a dictionary with at least 3 different  keys and values .

In [272]:
 f = { "artist" : "BTS" , "members" : 7 , "women" : False } # We create a  dictionary about BTS band

In [273]:
f

{'artist': 'BTS', 'members': 7, 'women': False}

g.We got the next courses list: 

In [274]:
courses = ["History", "Economy", "Anthropology", "Sociology ", "Literature"]

g.1.Add tree additional courses in 3 different ways( one for each way):
   - Sum (+) a list that contains an additional course. 
   - Use append. 
   - Use extend. 

In [275]:
courses = courses + ["Journalism"]  #We use + to add Journalism

In [276]:
courses

['History',
 'Economy',
 'Anthropology',
 'Sociology ',
 'Literature',
 'Journalism']

In [277]:
courses.append ("Arts") # We use append to add the second course

In [278]:
courses

['History',
 'Economy',
 'Anthropology',
 'Sociology ',
 'Literature',
 'Journalism',
 'Arts']

In [214]:
courses.extend (["Public Politics"]) # We use extend to add the third course

In [279]:
courses

['History',
 'Economy',
 'Anthropology',
 'Sociology ',
 'Literature',
 'Journalism',
 'Arts']

g.2.Use the indexation to stress _Sociology_.

In [280]:
courses [3] = "__Sociology__" #We use "_" to highlight this course

In [281]:
courses

['History',
 'Economy',
 'Anthropology',
 '__Sociology__',
 'Literature',
 'Journalism',
 'Arts']

g.3 Remove your least favourite course

In [282]:
courses.remove ("Economy") # We use remove() to eliminate Economy from the list, following Chat GPT advice

In [283]:
courses

['History',
 'Anthropology',
 '__Sociology__',
 'Literature',
 'Journalism',
 'Arts']

g.4. Invert the list

In [284]:
courses.reverse() # The reverse() method modifies the list, so we use it, following ChatGPT advice

In [285]:
courses

['Arts',
 'Journalism',
 'Literature',
 '__Sociology__',
 'Anthropology',
 'History']

h.Create a dictionary that representst a fruits inventory:
 - Add at least 5 fruits to the inventory
- Print the amount of apples in stock 
- Modify the amount of grapes


In [286]:
h = { "apples" : 5 , "grapes" : 9, "oranges" : 3, "lemons" : 2, "bananas" : 7 } # We create a dictionary with some fruits that we love during summer time

In [287]:
h["apples"] #We print the amount of apples

5

In [288]:
h["grapes"] = 10 #We modify the dictionary to add one more grapes

In [289]:
h 

{'apples': 5, 'grapes': 10, 'oranges': 3, 'lemons': 2, 'bananas': 7}

i.  Write a dictionary with the local GMT of the nexts cities:
- Antananarivo, Madagascar, 
- Beirut, Lebanon, 
- Jakarta, Indonesia, 
- Teherán, Iran, 
- Vientiane, Laos, 



Hint: Lima would be: `"Lima": -5`

In [290]:
i = { "Antananarivo, Madagascar": +3, "Beirut, Lebanon": +2, "Jakarta, Indonesia": +7, "Tehran, Iran": +3, "Vientiane, Laos": +7 }  #We search about each city and country and add the GMT

In [291]:
i

{'Antananarivo, Madagascar': 3,
 'Beirut, Lebanon': 2,
 'Jakarta, Indonesia': 7,
 'Tehran, Iran': 3,
 'Vientiane, Laos': 7}

 j.Add the nexts cities to the dictionary:
- Astana, Kazakhstan,
- Uagadugú, Burkina Faso,
- Balmopan, Belize

In [292]:
i["Astana, Kazakhstan"] = +5 
i["Ouagadougou, Burkina Faso"] = 0 
i["Belmopan, Belize"] = -6 #We search each country GMT

In [293]:
i

{'Antananarivo, Madagascar': 3,
 'Beirut, Lebanon': 2,
 'Jakarta, Indonesia': 7,
 'Tehran, Iran': 3,
 'Vientiane, Laos': 7,
 'Astana, Kazakhstan': 5,
 'Ouagadougou, Burkina Faso': 0,
 'Belmopan, Belize': -6}

# Part 3. Numpy


k.Create an array with 10 aleatory values that go from 0 to 9

In [294]:
import numpy as np

In [295]:
k = np.array ([0,1,3,5,7,9,6,8,2,5])  #We create an array manually with aleatory numbers

In [296]:
k

array([0, 1, 3, 5, 7, 9, 6, 8, 2, 5])

In [297]:
k_1= np.random.randint(0, 10, 10) #We create an array using random method with the help of Chat GPP

In [298]:
k_1

array([5, 4, 5, 1, 6, 1, 8, 6, 4, 8])

l.Create a matrix 3x2 fill with zeros

In [299]:
l = np.zeros ((3,2)) #We create a matrix using np.zeros and following instructions 3x2

In [300]:
l 

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

m.Sum two arrays and then multiply the output by an scalar

In [301]:
m_1 = np.random.randint(0, 3, 8)
m_2 = np.random.randint(0, 3, 8) #We create two random arrays with 8 values from 0 to 4

In [302]:
m_1

array([2, 0, 1, 1, 1, 0, 0, 0])

In [303]:
m_2

array([2, 2, 0, 1, 0, 2, 2, 2])

In [304]:
#After that we define a scalar 
m_total = m_1 + m_2 

scalar = 3 

#With that, we multiply the summed array by the scalar 

result = m_total* scalar

In [305]:
result

array([12,  6,  3,  6,  3,  6,  6,  6])

n.Create 2 arrays with the values that you wish :
- Concatenate vertically 
- Concatenate horizontally 

In [306]:
import numpy as np

In [307]:
n_1 = np.array ([0,3,5,7,8,2]) 
n_2 = np.array ([0,7,4,5,9,1]) #We use n.hstack to concatenate horizontally

In [308]:
n_1

array([0, 3, 5, 7, 8, 2])

In [309]:
n_2

array([0, 7, 4, 5, 9, 1])

In [310]:
n_h = np.hstack((n_1, n_2)) # We use np.hstack to concatenate horizontally

In [311]:
n_h

array([0, 3, 5, 7, 8, 2, 0, 7, 4, 5, 9, 1])

In [312]:
n_v = np.vstack((n_1, n_2)) # We use np.vstack to concatenate vertically

In [313]:
n_v

array([[0, 3, 5, 7, 8, 2],
       [0, 7, 4, 5, 9, 1]])