# Assignment_1
If you copy codes from previous answers, explain each step. No explanation is `0 points`.

##  Part 1.Data types


a.Declare one variable for each one these types: : int , float , string , boolean.
- Print  the varible's type using  type () function




In [231]:
variable_1 = 5 # we create a variable for each type and then we use type function to confirm

In [232]:
type(variable_1)

int

In [233]:
variable_2 = 5.0

In [234]:
type(variable_2)

float

In [235]:
variable_3 = "olenka, rennzo, santiago"

In [236]:
type(variable_3)

str

In [237]:
variable_4 = 5>3

In [238]:
type(variable_4)

bool

 b. Using only the following inputs: ```5``` and ```2```  ,  work the  operators to get the output  : ```50```

In [239]:
variable_5 = (5+5-2)*5+5*2 #We use the inputs and get the results using mathematical operators

In [240]:
variable_5

50

c. Evaluate if the output of the previous excercise is over 100. Create a variable that makes this evaluation. (Hint: It would be a boolean).

In [241]:
variable_6 = variable_5>100 #We create the variable and then evaluate if this output was true or false

In [242]:
variable_6

False

d. Create a variable equal to a list that contains: 
- a string,
- a boolean,
- two numeric values ( of any kind)  and
- a  list of two strings with the names of your favourite musical artists. 

In [243]:
variable_7 = ["medialab2025", True, 100, 23, ["taylor swift", "the strokes"]] #We create a list that contains everything requested in the exercise

In [244]:
variable_7

['medialab2025', True, 100, 23, ['taylor swift', 'the strokes']]

## Part 2. Containers

e. Create a tuple with 3 elements. Explain why you can't modify it. 

In [245]:
variable_8 = (200, 50, "troy bolton") #We create a tuple with random numbers and a name

In [246]:
# A tuple cannot be modified because it is immutable, which means that data cannot be added, modified, or deleted after it is created

f.Create a dictionary with at least 3 different  keys and values .

In [247]:
variable_9 = {"name":"rennzo","lastname":"contreras", "nickname":"fernandito"} #We create a dictionary about our partner Rennzo and we tested it

In [248]:
variable_9

{'name': 'rennzo', 'lastname': 'contreras', 'nickname': 'fernandito'}

In [249]:
variable_9["name"]

'rennzo'

g.We got the next courses list: 

In [250]:
courses_1 = ["History", "Economy", "Anthropology", "Sociology ", "Literature"]

g.1.Add tree additional courses in 3 different ways( one for each way):
   - Sum (+) a list that contains an additional course. 
   - Use append. 
   - Use extend. 

In [251]:
courses_3 = ["Art"]

In [252]:
courses_1 + courses_3

['History', 'Economy', 'Anthropology', 'Sociology ', 'Literature', 'Art']

In [253]:
courses_4 = ["Politics"]

In [254]:
courses_1.append(courses_4)

In [255]:
print(courses_1)

['History', 'Economy', 'Anthropology', 'Sociology ', 'Literature', ['Politics']]


In [256]:
courses_5 = ["Python"]

In [257]:
courses_1.extend(courses_5)

In [258]:
print(courses_1)

['History', 'Economy', 'Anthropology', 'Sociology ', 'Literature', ['Politics'], 'Python']


In [259]:
# We add the courses according to the instructions, and after using the append method, the list courses1 was affected. Therefore, when we used extend, the new list showed the new value added in append

g.2.Use the indexation to stress _Sociology_.

In [260]:
courses_1 [3] # We use the indexation to find the value "Sociology" and then we highlighted it by placing two x's on each side of the word

'Sociology '

In [261]:
courses_1 [3] = "xxSociologyxx"

In [262]:
courses_1 [3]

'xxSociologyxx'

In [263]:
courses_1

['History',
 'Economy',
 'Anthropology',
 'xxSociologyxx',
 'Literature',
 ['Politics'],
 'Python']

g.3 Remove your least favourite course

In [264]:
courses_1.remove ("Python") # We chose to delete the object by searching for it manually and not using indexation, then we verified that it was deleted

In [265]:
courses_1

['History',
 'Economy',
 'Anthropology',
 'xxSociologyxx',
 'Literature',
 ['Politics']]

g.4. Invert the list

In [266]:
courses_1.reverse () # We use the reverse method for this asignment

In [267]:
courses_1

[['Politics'],
 'Literature',
 'xxSociologyxx',
 'Anthropology',
 'Economy',
 'History']

h.Create a dictionary that represents a fruits inventory:
 - Add at least 5 fruits to the inventory
- Print the amount of apples in stock 
- Modify the amount of grapes


In [268]:
fruits = {"bananas":10, "coconuts":20,"apples":2,"grapes":1 ,"kiwis":3  } #We create the dictionary and follow the steps

In [269]:
fruits["apples"]

2

In [270]:
fruits["grapes"]=100

In [271]:
fruits["grapes"]

100

i.  Write a dictionary with the local GMT of the nexts cities:
- Antananarivo, Madagascar, 
- Beirut, Lebanon, 
- Jakarta, Indonesia, 
- Teherán, Iran, 
- Vientiane, Laos, 



Hint: Lima would be: `"Lima": -5`

In [272]:
GMT =   {"Antananarivo":+3,"Beirut":+2,"Jakarta":+7,"Teherán":+3.30,"Vientiane":+7  } #We search the GMT and create the dictionary

 j.Add the nexts cities to the dictionary:
- Astana, Kazakhstan,
- Uagadugú, Burkina Faso,
- Balmopan, Belize

In [273]:
GMT["Astana"]=+5 # We add the remain cities creating lists
GMT["Uagadugú"]=0
GMT["Balmopan"]=-6

In [274]:
GMT

{'Antananarivo': 3,
 'Beirut': 2,
 'Jakarta': 7,
 'Teherán': 3.3,
 'Vientiane': 7,
 'Astana': 5,
 'Uagadugú': 0,
 'Balmopan': -6}

# Part 3. Numpy


k.Create an array with 10 aleatory values that go from 0 to 9

In [ ]:
#we used Chatpt4#

In [275]:
import numpy as np # we import numpt library

In [281]:
variable_10= np.random.randint(0,50,10) #we create an array using a ramdom methot  using copilot, we take the 10 numbers between 0 and 50 #
variable_10

array([ 8, 27, 41, 10, 30, 42, 37, 42,  9, 38])

l.Create a matrix 3x2 fill with zeros

In [286]:

zero_variable= np.zeros((3,2)) #we indicate that we want a matrix of 3 files and 2 columns#
zero_variable #the n.zero let us create a matrix with the value of Ceros#

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

m.Sum two arrays and then multiply the output by an scalar

In [289]:
#first we create two arrays. Both arrays hadve the rage between 0-10, with eight values#
variable_mult1 = np.random.randint(0, 10, 8)
variable_mult2 = np.random.randint(0, 10, 8)

In [311]:
print(variable_mult1 )
print(variable_mult2)

[3 1 9 8 1 3 7 4]
[5 3 7 1 4 4 2 3]


n.Create 2 arrays with the values that you wish :
- Concatenate vertically 
- Concatenate horizontally 

In [312]:
#now we define the scalar al 3#
scalar = 2

In [313]:
variable_result = variable_mult1 +variable_mult2

In [314]:
variable_scal = sum_result * scalar

In [315]:
print(variable_scal) #we show the final results#

[16  8 32 18 10 14 18 14]


Create 2 arrays with the values that you wish

- Concatenate vertically
- Concatenate horizontally

In [316]:
#we firts define the arrays#
varibl_c1 = np.array([10, 25, 37, 48])
varibl_c2 = np.array([58, 96, 17, 18])

In [318]:
#we first define a verticaly and them horizontaly#
varibl_cont1 = np.vstack((varibl_c1, varibl_c2))
varibl_cont2 = np.hstack((varibl_c1, varibl_c2))


In [321]:
#we show the final result#
print(varibl_cont1)
print(varibl_cont2)
      


[[10 25 37 48]
 [58 96 17 18]]
[10 25 37 48 58 96 17 18]
